package main.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.LineBorder;

import main.control.Controller;
import main.palazzetti.interfaces.Tavolo;

/**
 *
 * @author milena
 */
public class RistFrame extends javax.swing.JFrame {

    private final Controller controller;
    private final View view;
    private final Map<Tavolo, JPanel> tavoliMap;
    private String defaultPath = "/home/milena/Documenti/Coding/progetto_pmo_202425/simulazione_ristorante/Prodotti.json";
    
    /**
     * Creates new form RistoranteFrame
     */
    public RistFrame(Controller controller, View view) {
        this.controller = controller;
		this.view = view;
        this.tavoliMap = new HashMap<>();

        setTitle("Simulazione Ristorante");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(800, 600);
        setLayout(new BorderLayout());
        setVisible(true);

        initComponents();

    }

    public void inizializzaTavoli() {
        for (Tavolo t : controller.getTavoli()) {
            JPanel tavoloPanel = new JPanel();
            tavoloPanel.setPreferredSize(new Dimension(120, 80));
            tavoloPanel.setBackground(t.isOccupato() ? Color.RED : Color.GREEN);
            tavoloPanel.setBorder(new LineBorder(Color.BLACK, 2));
            tavoloPanel.setLayout(new GridLayout(3, 1));

            tavoloPanel.add(new JLabel("Tavolo: " + t.getNumero()));
            tavoloPanel.add(new JLabel("Posti: " + t.getNumeroPosti()));
            tavoliMap.put(t, tavoloPanel);
            innerTavoliPanel.add(tavoloPanel);
        }

        innerTavoliPanel.revalidate();
        innerTavoliPanel.repaint();

    }

    public void aggiornaTavoli() {
        for (Map.Entry<Tavolo, JPanel> entry : tavoliMap.entrySet()) {
            Tavolo tavolo = entry.getKey();
            JPanel bottone = entry.getValue();

            if (tavolo.isOccupato()) {
                bottone.setBackground(Color.RED);
            } else {
                bottone.setBackground(Color.GREEN);
            }
        }

        tavoliPanel.revalidate();
        tavoliPanel.repaint();
    }

    public int getNumTavoli(){
        return (int)tavoliSpin.getValue();
    }
    
    public int getNumClienti(){
        return (int)clientiSpin.getValue();
    }
    
    public int getDurataInserita(){
        return (int)durataSpin.getValue();
    }
    
    public String getPathInserito(){
        return percorsoField.getText();
    }
    
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                         
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        logPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        tavoliPanel = new javax.swing.JPanel();
        innerTavoliPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientiSpin = new javax.swing.JSpinner(new SpinnerNumberModel(20, 1, 100, 1));
        jLabel9 = new javax.swing.JLabel();
        tavoliSpin = new javax.swing.JSpinner(new SpinnerNumberModel(20, 1, 100, 1));
        jLabel11 = new javax.swing.JLabel();
        durataSpin = new javax.swing.JSpinner(new SpinnerNumberModel(5, controller.getDurataMinimaSimulazione(), controller.getDurataMassimaSimulazione(), 1));
        buttonPanel = new javax.swing.JPanel();
        avviaButton = new javax.swing.JButton();
        fermaButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        percorsoField = new javax.swing.JTextField();
        apriButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        gruppiPanel = new javax.swing.JPanel();
        gruppiPanelLabel = new javax.swing.JLabel();
        gruppiPanelScroll = new javax.swing.JScrollPane();
        gruppiPanelTA = new javax.swing.JTextArea();
        ordiniPanel = new javax.swing.JPanel();
        ordiniPanelLabel = new javax.swing.JLabel();
        ordiniPanelScroll = new javax.swing.JScrollPane();
        ordiniPanelTA = new javax.swing.JTextArea();
        richiesteContoPanel = new javax.swing.JPanel();
        rcPanelLabel = new javax.swing.JLabel();
        rcPanelScroll = new javax.swing.JScrollPane();
        rcPanelTA = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        topPanel.setBackground(new java.awt.Color(51, 255, 51));
        topPanel.setLayout(new java.awt.BorderLayout());

        logPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Simulazione");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        logScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        logTextArea.setColumns(20);
        logTextArea.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        logTextArea.setRows(5);
        logTextArea.setBorder(null);
        logTextArea.setEditable(false);
        logScrollPane.setViewportView(logTextArea);

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        topPanel.add(logPanel, java.awt.BorderLayout.WEST);

        tavoliPanel.setBackground(new java.awt.Color(255, 255, 255));

        innerTavoliPanel.setBackground(new java.awt.Color(228, 228, 228));
        innerTavoliPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        innerTavoliPanel.setLayout(new java.awt.GridLayout(4, 5));
        innerTavoliPanel.setPreferredSize(new Dimension(600, 320));


        javax.swing.GroupLayout tavoliPanelLayout = new javax.swing.GroupLayout(tavoliPanel);
        tavoliPanel.setLayout(tavoliPanelLayout);
        tavoliPanelLayout.setHorizontalGroup(
            tavoliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tavoliPanelLayout.createSequentialGroup()
                .addComponent(innerTavoliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tavoliPanelLayout.setVerticalGroup(
            tavoliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tavoliPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innerTavoliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        topPanel.add(tavoliPanel, java.awt.BorderLayout.CENTER);

        settingsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Impostazioni");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setText("Numero clienti:");

        jLabel9.setText("Numero tavoli:");

        jLabel11.setText("Durata simulazione:");

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        avviaButton.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        avviaButton.setText("Avvia");
        avviaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avviaButtonActionPerformed(evt);
            }
        });

        fermaButton.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        fermaButton.setText("Ferma");
        fermaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(avviaButton)
                .addGap(18, 18, 18)
                .addComponent(fermaButton)
                .addGap(35, 35, 35))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fermaButton)
                    .addComponent(avviaButton))
                .addContainerGap())
        );

        jLabel4.setText("Menu:");

        percorsoField.setFont(new java.awt.Font("Roboto Condensed", 0, 13)); // NOI18N
        percorsoField.setText(defaultPath);

        apriButton.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        apriButton.setText("Apri");
        apriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apriButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                                .addComponent(apriButton)
                                .addContainerGap())))
                    .addGroup(settingsPanelLayout.createSequentialGroup()
                        .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clientiSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tavoliSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(durataSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(percorsoField)))
                        .addContainerGap())))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientiSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tavoliSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(durataSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(percorsoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apriButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        topPanel.add(settingsPanel, java.awt.BorderLayout.EAST);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setLayout(new java.awt.GridLayout());

        gruppiPanel.setBackground(new java.awt.Color(255, 255, 255));
        gruppiPanel.setLayout(new java.awt.BorderLayout());

        gruppiPanelLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        gruppiPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gruppiPanelLabel.setText("Gruppi in attesa");
        gruppiPanelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gruppiPanel.add(gruppiPanelLabel, java.awt.BorderLayout.NORTH);

        gruppiPanelTA.setColumns(20);
        gruppiPanelTA.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        gruppiPanelTA.setRows(5);
        gruppiPanelScroll.setViewportView(gruppiPanelTA);

        gruppiPanel.add(gruppiPanelScroll, java.awt.BorderLayout.CENTER);

        bottomPanel.add(gruppiPanel);

        ordiniPanel.setBackground(new java.awt.Color(255, 255, 255));
        ordiniPanel.setLayout(new java.awt.BorderLayout());

        ordiniPanelLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        ordiniPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordiniPanelLabel.setText("Ordini in attesa");
        ordiniPanelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ordiniPanel.add(ordiniPanelLabel, java.awt.BorderLayout.NORTH);

        ordiniPanelTA.setColumns(20);
        ordiniPanelTA.setRows(5);
        ordiniPanelScroll.setViewportView(ordiniPanelTA);

        ordiniPanel.add(ordiniPanelScroll, java.awt.BorderLayout.CENTER);

        bottomPanel.add(ordiniPanel);

        richiesteContoPanel.setBackground(new java.awt.Color(255, 255, 255));
        richiesteContoPanel.setLayout(new java.awt.BorderLayout());

        rcPanelLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        rcPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rcPanelLabel.setText("Richieste conto");
        rcPanelLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        richiesteContoPanel.add(rcPanelLabel, java.awt.BorderLayout.NORTH);

        rcPanelTA.setColumns(20);
        rcPanelTA.setRows(5);
        rcPanelScroll.setViewportView(rcPanelTA);

        richiesteContoPanel.add(rcPanelScroll, java.awt.BorderLayout.CENTER);

        bottomPanel.add(richiesteContoPanel);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel7, java.awt.BorderLayout.NORTH);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel7.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        bottomPanel.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel8, java.awt.BorderLayout.NORTH);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jPanel8.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        bottomPanel.add(jPanel8);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void apriButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JFileChooser fileChooser = new JFileChooser();
        int risultato = fileChooser.showOpenDialog(this);

        if (risultato == JFileChooser.APPROVE_OPTION) {
            File fileSelezionato = fileChooser.getSelectedFile();
            String percorso = fileSelezionato.getAbsolutePath();
            System.out.println("Hai scelto: " + percorso);

            percorsoField.setText(fileSelezionato.getAbsolutePath());
        }
    }  

    private void avviaButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        view.notificaSimulazioneAvviata();
    }                                        

    private void fermaButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        view.notificaSimulazioneFermata();
    }                                        

    // Variables declaration - do not modify                     
    private JPanel bottomPanel;
    private JPanel buttonPanel;
    private JPanel gruppiPanel;
    private JLabel gruppiPanelLabel;
    private JScrollPane gruppiPanelScroll;
    private JTextArea gruppiPanelTA;
    private JButton avviaButton;
    private JButton fermaButton;
    private JButton apriButton;
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel innerTavoliPanel;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JScrollPane logScrollPane;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JSpinner clientiSpin;
    private JSpinner tavoliSpin;
    private JSpinner durataSpin;
    private JTextArea logTextArea;
    private JTextArea jTextArea2;
    private JTextArea jTextArea4;
    private JTextField percorsoField;
    private JPanel logPanel;
    private JPanel mainPanel;
    private JPanel ordiniPanel;
    private JLabel ordiniPanelLabel;
    private JScrollPane ordiniPanelScroll;
    private JTextArea ordiniPanelTA;
    private JLabel rcPanelLabel;
    private JScrollPane rcPanelScroll;
    private JTextArea rcPanelTA;
    private JPanel richiesteContoPanel;
    private JPanel settingsPanel;
    private JPanel tavoliPanel;
    private JPanel topPanel;
    // End of variables declaration                   
}
